# Generated by Django 2.2.7 on 2019-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(verbose_name='date recorded')),
                ('AQ', models.IntegerField(max_length=100)),
                ('CO2', models.IntegerField(max_length=100)),
            ],
        ),
    ]
