# Generated by Django 2.2.7 on 2019-11-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestReceiver', '0002_auto_20191127_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='dateTime',
            field=models.CharField(max_length=100),
        ),
    ]
